[package]
name = "hanihi-mcp-server"
version = "0.1.0"
edition = "2024"
description = "MCP Server for Hānihi"
default-run = "hanihi-mcp-server-ro"
autobins = false

[dependencies]
chrono = "0.4.45"
regex = "1.13.1"
serde = {version = "1.0.229", features = [
    "derive",
    "rc",
],}
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.10"

[[bin]]
name = "hanihi-mcp-server-ro"
path = "src/main.rs"

[[bin]]
name = "hanihi-mcp-server-rw"
path = "src/bin/hanihi-mcp-server-rw.rs"
