[package]
name = "kakahu-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
kakahu-core = { version = "0.1.0", path = "../kakahu-core" }
clap = { version = "4.6.6", features = ["derive", "env"] }
reedline = "0.49.0"
rig = { package = "rig-core", version = "0.41.0" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
